// AUTO-GENERATED - DO NOT EDIT MANUALLY
// Generated by: scripts/src/07_export_for_move.py
// Timestamp: 2025-12-06T13:44:23.511335
// Function: erf
// Max approximation error: 5.67e-11
// Domain: [0, 6]

module gaussian::erf_coefficients;

/// Scale factor (WAD = 10^18)
const SCALE: u256 = 1_000_000_000_000_000_000;

/// Number of numerator coefficients
const P_DEGREE: u64 = 11;

/// Number of denominator coefficients
const Q_DEGREE: u64 = 11;

// Numerator P(x) coefficients
// P(x) = P0 + P1*x + P2*x² + ... + P11*x^11

const P0: u256 = 0;
const P0_NEG: bool = false;
const P1: u256 = 1128379170753457800;
const P1_NEG: bool = false;
const P2: u256 = 1044655768089819600;
const P2_NEG: bool = true;
const P3: u256 = 608349995442425500;
const P3_NEG: bool = false;
const P4: u256 = 175342732597393000;
const P4_NEG: bool = true;
const P5: u256 = 37275649725247606;
const P5_NEG: bool = false;
const P6: u256 = 5145192681373998;
const P6_NEG: bool = true;
const P7: u256 = 3714637344099715;
const P7_NEG: bool = false;
const P8: u256 = 1857962888096386;
const P8_NEG: bool = true;
const P9: u256 = 700919546278180;
const P9_NEG: bool = false;
const P10: u256 = 136755077270363;
const P10_NEG: bool = true;
const P11: u256 = 16501013491964;
const P11_NEG: bool = false;

// Denominator Q(x) coefficients
// Q(x) = Q0 + Q1*x + Q2*x² + ... + Q11*x^11

const Q0: u256 = 1000000000000000000;
const Q0_NEG: bool = false;
const Q1: u256 = 925801939222393200;
const Q1_NEG: bool = true;
const Q2: u256 = 872467634826446500;
const Q2_NEG: bool = false;
const Q3: u256 = 463980353011229030;
const Q3_NEG: bool = true;
const Q4: u256 = 223794185627340210;
const Q4_NEG: bool = false;
const Q5: u256 = 66446673751336090;
const Q5_NEG: bool = true;
const Q6: u256 = 14039731030396678;
const Q6_NEG: bool = false;
const Q7: u256 = 1191550425858858;
const Q7_NEG: bool = false;
const Q8: u256 = 1627031863036735;
const Q8_NEG: bool = true;
const Q9: u256 = 686930751920809;
const Q9_NEG: bool = false;
const Q10: u256 = 136251257363812;
const Q10_NEG: bool = true;
const Q11: u256 = 16492859370954;
const Q11_NEG: bool = false;

// Getter functions (for use by erf module)

public fun scale(): u256 { SCALE }

public fun p_degree(): u64 { P_DEGREE }

public fun q_degree(): u64 { Q_DEGREE }

/// Get numerator coefficient at index i
public fun p_coeff(i: u64): (u256, bool) {
    if (i == 0) { (P0, P0_NEG) } else if (i == 1) { (P1, P1_NEG) } else if (i == 2) { (P2, P2_NEG) }
    else if (i == 3) { (P3, P3_NEG) } else if (i == 4) { (P4, P4_NEG) } else if (i == 5) {
        (P5, P5_NEG)
    } else if (i == 6) { (P6, P6_NEG) } else if (i == 7) { (P7, P7_NEG) } else if (i == 8) {
        (P8, P8_NEG)
    } else if (i == 9) { (P9, P9_NEG) } else if (i == 10) { (P10, P10_NEG) } else { (P11, P11_NEG) }
}

/// Get denominator coefficient at index i
public fun q_coeff(i: u64): (u256, bool) {
    if (i == 0) { (Q0, Q0_NEG) } else if (i == 1) { (Q1, Q1_NEG) } else if (i == 2) { (Q2, Q2_NEG) }
    else if (i == 3) { (Q3, Q3_NEG) } else if (i == 4) { (Q4, Q4_NEG) } else if (i == 5) {
        (Q5, Q5_NEG)
    } else if (i == 6) { (Q6, Q6_NEG) } else if (i == 7) { (Q7, Q7_NEG) } else if (i == 8) {
        (Q8, Q8_NEG)
    } else if (i == 9) { (Q9, Q9_NEG) } else if (i == 10) { (Q10, Q10_NEG) } else { (Q11, Q11_NEG) }
}
